### ISSUE TITLE
glGetTexParameter() parameters are wrong

### ISSUE THREAD

**Issue by william-shere** [sriharshachilakapati/WebGL4J#6]
The first parameter of glGetTexParameter() is supposed to be the texture target but WebGL4J expects a texture ID. Since this is mapped to the native JSON object before being passed to OpenGL it results in an INVALID_ENUM error.

**Comment by sriharshachilakapati** [comment]
Sorry for the late reply, I've been super busy attending interviews and with college projects. I've seen this and confirmed that it is indeed a bug. I'll fix this tonight once I return home.

**Comment by sriharshachilakapati** [comment]
This is fixed in `4cf3d68` commit, thank you for bringing this to my notice.

**Comment by sriharshachilakapati** [comment]
@Quew8 After some testing, this is now up in the latest release 0.2.9. Use the dependency string

~~~groovy
compile 'com.goharsha:webgl4j:0.2.9'
~~~
